spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/anpr-mgmt
    username: abhijit
    password: abhijit
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          bath_size: 1000
        order_inserts: true

logging:
  level:
    root: INFO
    com.bizservice: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"   # expose everything locally

server:
  port: 8080